### PR TITLE
Bugfix/t UI 357 cancel job button

### PR DESCRIPTION
**Pull request by carrythemountain**
## Related Github Issues:

- [TUI-1234](https://github.com/tapis-project/tapis-ui/issues/1234)

## Testing Steps:

1.

### CODE REVIEW

**Review by nathandf — CHANGES_REQUESTED** [review]
Great work sir. And fast, thanks.

I would just ask that you add some screenshots of the UI that capture your changes

**Comment by carrythemountain** [comment]
Screenshot 2024-08-28 at 2 33 29 PM
Screenshot 2024-08-28 at 2 34 08 PM
Screenshot 2024-08-28 at 2 34 50 PM

**Comment by nathandf** [comment]
i see an error in the second screenshot. The Cancel button should be disabled for jobs with a status of CANCELED but it's not

**Comment by carrythemountain** [comment]
> i see an error in the second screenshot. The Cancel button should be disabled for jobs with a status of CANCELED but it's not

My apologies, these are uploaded out of order. The first shows the latter of the changes, the second shows the former.

**Comment by nathandf** [comment]
By former, do you mean what it looked like before you made the changes?

**Review by nathandf — APPROVED** [review]

**Pull request merged**
